source 'http://rubygems.org'

gem 'sinatra'
gem 'activerecord', '4.2.5', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake'
gem 'require_all'
gem 'sqlite3'
gem 'thin'
gem 'shotgun'
gem 'pry'
gem 'bcrypt'
gem 'tux'
gem 'nokogiri'
# require 'open-uri' #open-uri is part of Ruby standard library, that's why only need to require, not installß
